name: ggmud
on:
  push:
jobs:
  build-project:
    name: ggmud
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          source-dir: ggmud/
